export const LOAD_TODOS_STARTED = 'LOAD_TODOS_STARTED';
export const LOAD_TODOS_SUCCESS = 'LOAD_TODOS_SUCCESS';
export const LOAD_TODOS_FAILURE = 'LOAD_TODOS_FAILURE';

export const ADD_TODO_STARTED = 'ADD_TODO_STARTED';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';

export const REMOVE_TODO_STARTED = 'REMOVE_TODO_STARTED';
export const REMOVE_TODO_FAILURE = 'REMOVE_TODO_FAILURE';

export const UPDATE_TODO = 'UPDATE_TODO';
